### ISSUE TITLE
Error occured when using SAHI to process mva2023_sod4bird_train

### ISSUE THREAD

**Issue by WooXinyi** [IIM-TTIJ/MVA2023SmallObjectDetection4SpottingBirds#10]
I guess the annotation of mva2023_sod4bird_train does't have standard coco format, for it is OK to process Drone2021 when using SAHI.
Please check and fix it, thanks.

**Comment by IIM-TTIJ** [comment]
Please share SAHI error logs to help us understand where the annotation file errors are coming from.

**Comment by WooXinyi** [comment]
### code
~~~
from sahi.scripts.slice_coco import slice


def slice_data(image_dir, dataset_json_path, output_dir, slice_size, overlap_ratio):
    slice(
        image_dir=image_dir,
        dataset_json_path=dataset_json_path,
        output_dir=output_dir,
        slice_size=slice_size,
        overlap_ratio=overlap_ratio)
~~~

### error log
~~~
Traceback (most recent call last):
  File "/home/qxc/miniconda3/envs/test/lib/python3.7/site-packages/sahi/scripts/slice_coco.py", line 59, in slice
    verbose=False,
  File "/home/qxc/miniconda3/envs/test/lib/python3.7/site-packages/sahi/slicing.py", line 487, in slice_coco
    verbose=verbose,
  File "/home/qxc/miniconda3/envs/test/lib/python3.7/site-packages/sahi/slicing.py", line 365, in slice_image
    sliced_coco_annotation_list = process_coco_annotations(coco_annotation_list, slice_bbox, min_area_ratio)
  File "/home/qxc/miniconda3/envs/test/lib/python3.7/site-packages/sahi/slicing.py", line 141, in process_coco_annotations
    if annotation_inside_slice(coco_annotation.json, slice_bbox):
  File "/home/qxc/miniconda3/envs/test/lib/python3.7/site-packages/sahi/slicing.py", line 106, in annotation_inside_slice
    left, top, width, height = annotation["bbox"]
ValueError: not enough values to unpack (expected 4, got 0)

~~~

**Comment by IIM-TTIJ** [comment]
We discovered a problem with the segmentation in the annotation file. We've fixed the issue and confirmed that the corresponding code is now functioning properly. We apologize for any inconvenience caused.

We have updated the annotation file on the download page, so please redownload it from there.

https://drive.google.com/drive/folders/1vTHiIelagbzPO795yhOdNUFh9u2XxZP-

**Comment by WooXinyi** [comment]
Great! I have successful processed mva2023_sod4bird_train with SAHI. Thanks.
